# Application Configuration
app:
  title: "Interactive AT Data Generator & Explorer"
  page_title: "AT Data Sandbox"
  layout: "wide"
  
# Data Generation Defaults
generation:
  participants:
    min: 50
    max: 2000
    default: 350
    step: 50
  
  plans:
    avg_per_participant:
      min: 0.5
      max: 3.0
      default: 1.2
      step: 0.1
    
    claims_per_plan:
      min: 1
      max: 20
      default_min: 4
      default_max: 10
    
    budget:
      min: 5000
      max: 60000
    
    duration_days: 365
  
  utilization:
    target:
      min: 0
      max: 100
      default: 60
    spread:
      min: 1
      max: 10
      default: 5
  
  processing_days:
    min: 0
    max: 30

# Business Data
lookup_data:
  states:
    - NSW
    - VIC
    - QLD
    - SA
    - WA
    - TAS
    - NT
    - ACT
  
  mmm_codes:
    - MMM1
    - MMM2
    - MMM3
    - MMM4
    - MMM5
    - MMM6
    - MMM7
  
  disabilities:
    - intellectual
    - cognitive
    - neurological
    - sensory
    - physical
    - psychosocial
  
  plan_management_modes:
    - Agency
    - Plan
    - Self
  
  variation_types:
    - Initial
    - Light-Touch
    - Full-Reassess

# Chart Configuration
charts:
  default_height: 400
  color_palette:
    - "#1f77b4"
    - "#ff7f0e"
    - "#2ca02c"
    - "#d62728"
    - "#9467bd"
    - "#8c564b"
    - "#e377c2"
    - "#7f7f7f"

# Date Configuration  
dates:
  pace_live_default: "2024-07-01"
  window_start_default: "2023-07-01"
  window_end_default: "2025-06-30"
  
# Random Seed
random:
  default_seed: 20250617
